# Generated by Django 4.2.13 on 2024-06-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0002_alter_letter_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
