# Generated by Django 4.2.13 on 2024-06-21 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matching', '0004_match_current_question'),
        ('letters', '0003_alter_letter_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='match',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='matching.match'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='receiver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='received_letters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='letter',
            name='sender',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sent_letters', to=settings.AUTH_USER_MODEL),
        ),
    ]
