# Generated by Django 5.0.6 on 2024-06-22 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0005_alter_letter_image_url'),
        ('matching', '0005_alter_matchrequest_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.match'),
        ),
    ]
