# Generated by Django 5.0.6 on 2024-06-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comment_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.CharField(blank=True, null=True),
        ),
    ]
