# Generated by Django 4.2.13 on 2024-06-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(default='type', max_length=30),
        ),
    ]
