# Generated by Django 4.2.13 on 2024-06-11 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('withdraw_reason', models.TextField(null=True)),
                ('acceptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_matches', to='accounts.user')),
                ('learning_lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_matches', to='accounts.language')),
                ('native_lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='native_matches', to='accounts.language')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_matches', to='accounts.user')),
            ],
        ),
    ]
