# Generated by Django 5.0.6 on 2024-06-11 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("withdraw_reason", models.TextField(null=True)),
                (
                    "acceptor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accepted_matches",
                        to="accounts.user",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requested_matches",
                        to="accounts.user",
                    ),
                ),
            ],
        ),
    ]
