# Generated by Django 5.0.6 on 2024-06-17 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0005_question'),
        ('matching', '0003_match_provided_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='current_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_match', to='interests.question'),
        ),
    ]
