# Generated by Django 5.0.6 on 2024-06-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("printers", "0002_rename_epsonconnectauth_epsonconnectemail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="epsonconnectscandata",
            name="imagefile",
            field=models.ImageField(upload_to="letters/"),
        ),
    ]
