# Generated by Django 5.0.6 on 2024-06-18 09:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("printers", "0003_alter_epsonconnectscandata_imagefile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="epsonconnectemail",
            name="deviceEmail",
        ),
    ]
