# Generated by Django 4.2.13 on 2024-06-18 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0002_alter_letter_image_url'),
        ('printers', '0004_remove_epsonconnectemail_deviceemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='epsonconnectscandata',
            name='letter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='letters.letter'),
        ),
    ]
