# Generated by Django 4.2.13 on 2024-06-20 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0005_epsonconnectscandata_letter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EpsonConnectEmail',
        ),
    ]
