# Generated by Django 5.0.6 on 2024-06-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0008_alter_epsonconnectscandata_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpsonGlobalImageShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField()),
            ],
        ),
    ]
