# Generated by Django 4.2.13 on 2024-06-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='image',
            field=models.FileField(null=True, upload_to='interests/'),
        ),
    ]
