# Generated by Django 5.0.6 on 2024-06-14 06:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interests", "0002_alter_interest_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="interest",
            name="name_eng",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
