# Generated by Django 4.2.13 on 2024-06-17 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0004_alter_interest_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interests.interest')),
            ],
        ),
    ]
