# Generated by Django 5.0.6 on 2024-06-24 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0006_question_engtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='image',
            field=models.CharField(null=True),
        ),
    ]
