# Generated by Django 5.0.6 on 2024-06-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("oauth_id", models.IntegerField()),
                ("nickname", models.CharField(max_length=30)),
                ("profile_image_url", models.TextField(null=True)),
                ("created_at", models.DateTimeField()),
                ("withdraw_at", models.DateTimeField(null=True)),
                ("language", models.IntegerField()),
                ("printer_status", models.BooleanField()),
                ("is_loggined", models.BooleanField()),
                ("withdraw_reason", models.TextField(null=True)),
                ("email", models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
