# Generated by Django 4.2.13 on 2024-06-15 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30)),
                ('profile_image_url', models.FileField(null=True, upload_to='accounts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('withdraw_at', models.DateTimeField(null=True)),
                ('printer_status', models.BooleanField(default=False)),
                ('is_loggined', models.BooleanField(default=False)),
                ('withdraw_reason', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.language')),
                ('oauth_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth.oauthuser')),
            ],
        ),
    ]
