# Generated by Django 4.2.13 on 2024-06-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_loggined',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='printer_status',
            field=models.BooleanField(default=False),
        ),
    ]
