# Generated by Django 4.2.13 on 2024-06-15 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL('CREATE TABLE IF NOT EXISTS accounts_language (id SERIAL PRIMARY KEY, lang_name VARCHAR(30) NOT NULL);')
    ]
