# Generated by Django 4.2.13 on 2024-06-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_is_loggined_alter_user_printer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image_url',
            field=models.FileField(null=True, upload_to='accounts/'),
        ),
    ]
