# Generated by Django 5.0.6 on 2024-06-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_oauth_id_user_last_login_user_oauth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='printer_status',
        ),
        migrations.AddField(
            model_name='user',
            name='epson_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
