# Generated by Django 5.0.6 on 2024-06-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_status_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status_message',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
