# Generated by Django 5.0.6 on 2024-06-22 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_status_message'),
        ('accounts', '0005_user_level'),
    ]

    operations = [
    ]
